### PR TITLE
Try using HTTP gateways if IPFS get fails

### LINKED ISSUE #1102: Try to resolve layers using HTTP gateways if IPFS operation fails
API example: 
https://gateway.pinata.cloud/api/v0/get?arg=Qmf24DLiVqXfpQtzWzmN8cRuYYLmNACKeA58ccjLqD2557&archive=true

### PR DESCRIPTION
**Pull request by odisseus**
I have checked manually that this works.

Closes #1102.

### CODE REVIEW

File: src/core/external.scala [hunk 1]
```diff
@@ -32,6 +32,11 @@ object Ipfs {
   import io.ipfs.api._
   import io.ipfs.multihash.Multihash
 
+  private val knownGateways = List(
```
Comment (propensive) [inline src/core/external.scala:35]: Good to build in some sort of choice. I'd like to make this configurable, but only once I've done a small overhaul of the configuration interface. (Issue #900)

File: src/core/external.scala [hunk 2]
```diff
@@ -40,7 +45,15 @@ object Ipfs {
       IpfsRef(top.hash.toBase58)
     }
 
-    def get(ref: IpfsRef, path: Path): Try[Path] = getFile(Multihash.fromBase58(ref.key), path)
+    def get(ref: IpfsRef, path: Path)(implicit log: Log): Try[Path] = {
+      val hash = Multihash.fromBase58(ref.key)
+      getFile(hash, path).recoverWith { case e =>
+        log.warn(s"Could not resolve the hash using IPFS daemon")
+        val gateway = Random.shuffle(knownGateways).head
```
Comment (propensive) [inline src/core/external.scala]: I think that determinism would be better, though I also get the idea that building a tool which builds in a third-party service without a SLA isn't a good idea. But we will make it configurable.

File: src/core/external.scala [hunk 3]
```diff
@@ -40,7 +45,15 @@ object Ipfs {
...
+        log.warn(s"Trying $gateway")
```
Comment (propensive) [inline src/core/external.scala]: Use `info` instead of `warn`.

File: src/core/external.scala [hunk 4]
```diff
@@ -63,6 +76,15 @@ object Ipfs {
       _    =  TarGz.untar(in, path)
     } yield path.childPaths.head
 
+    private def getFileFromGateway(hash: Multihash, path: Path)(gateway: String)(implicit log: Log): Try[Path] = {
+      for {
+        _    <- path.mkParents()
+        data <- Http.get(Https(Path(gateway) / "api" / "v0" / s"get?arg=${hash.toBase58}&archive=true"), Map(), Set.empty)
```
Comment (propensive) [inline src/core/external.scala]: Is this URL better than `https://<gateway>/ipfs/<hash>`? It avoids directories being displayed through an HTML web interface, right?

**Review by propensive — CHANGES_REQUESTED** [review]

File: src/core/external.scala (hunk 2 above)
Comment (odisseus) [reply src/core/external.scala]: I don't want all the users to hit the same gateway all the time, so I think it is better to choose one at random. On the other hand, this feature is going to be used very rarely (I hope), and it should not make any significant impact on any gateway.

File: src/core/external.scala (hunk 3 above)
Comment (odisseus) [reply src/core/external.scala]: This state is an error, although a recoverable one. Therefore, I think the warn level is appropriate here.

File: src/core/external.scala (hunk 4 above)
Comment (odisseus) [reply src/core/external.scala]: This is [part](https://docs.ipfs.io/reference/api/http/#api-v0-get) of the standard HTTP interface of an IPFS node. This particular endpoint allows to download a directory as a single TAR file.

File: src/core/external.scala (hunk 1 above)
Comment (odisseus) [reply src/core/external.scala:35]: Does the configuration format support lists of values?

Comment (odisseus) [reply src/core/external.scala:35]: See #1115.

File: src/core/external.scala (hunk 2 above)
Comment (odisseus) [reply src/core/external.scala]: The shuffling has been removed.

File: src/core/external.scala (hunk 3 above)
Comment (odisseus) [reply src/core/external.scala]: Done

File: src/core/external.scala (hunk 1 above)
Comment (propensive) [reply src/core/external.scala:35]: Yes, it does. We have an OGDL [de]serializer for `List[T]`.

File: src/core/external.scala [hunk 5]
```diff
@@ -56,13 +72,24 @@ object Ipfs {
...
+    private[this] def getFile(hash: Multihash, path: Path): Try[Path] = for {
       _    <- path.mkParents()
       data =  api.get(hash)
       in   =  new ByteArrayInputStream(data)
       _    =  TarGz.untar(in, path)
     } yield path.childPaths.head
 
+    private[this] def getFileFromGateway(hash: Multihash, path: Path)(gateway: String)(implicit log: Log): Try[Path] = {
+      log.info(s"Accessing $gateway to retrieve $hash")
+      val query = Query & "arg" -> hash.toBase58 & "archive" -> "true"
```
Comment (propensive) [inline src/core/external.scala]: Whilst the syntax for `Query` is novel, I think I would prefer something more similar to a `ListMap`, i.e. an ordered map. My main concern is the introduction of `&` as an operator. It needs to have weaker precedence than `->` in order to work, and this isn't so clear. I think it would make sense to write this as, `Query("arg" -> hash.toBase58, "archive" -> "true")` or `Query(ListMap("arg" -> hash.toBase58, "archive" -> "true"))`.

File: src/core/external.scala [hunk 6]
```diff
@@ -56,13 +72,24 @@ object Ipfs {
       )
     }
 
-    private def getFile(hash: Multihash, path: Path): Try[Path] = for {
+    private[this] def getFile(hash: Multihash, path: Path): Try[Path] = for {
```
Comment (propensive) [inline src/core/external.scala:75]: There needs to be a timeout on here, otherwise it will never terminate and will never fall back to using HTTP.

**Review by propensive — CHANGES_REQUESTED** [review]
I think we need something extra in the logic for when to use HTTP and when to use IPFS:
- if the user has IPFS installed on the `PATH` or a Fury-managed installation, use it, falling back to HTTP if the request times out
- if not, and the user is doing an IPFS `add` operation, install IPFS into order to perform the operation
- if not, use the HTTP gateway without installing IPFS.

In other words: use IPFS if we have it, install it only if we need it, otherwise use HTTP, and use HTTP if IPFS times out.

File: src/core/external.scala (hunk 6 above)
Comment (odisseus) [reply src/core/external.scala:75]: That's a good point, but I'd rather do it in another pull request. In fact, I think these requests do terminate eventually, but this happens after 10 or so minutes due to gateway timeout on the server.

**Comment by odisseus** [comment]
Regarding the usage of IPFS gateways vs setting up a local node, I think the local node should be used as much as possible. This will avoid the strain on the gateways and make the user independent of them. There is even an [opinion](https://medium.com/pinata/the-ipfs-gateway-problem-64bbe7eb8170) that public gateways do a disservice to the IPFS community.

File: src/core/external.scala (hunk 5 above)
Comment (odisseus) [reply src/core/external.scala]: The current syntax allows adding more parentheses to make the priority of operations more clear:
```
val query1 = Query & ("arg" -> hash.toBase58) & ("archive" -> "true")
val query2 = Query & ("arg", hash.toBase58) & ("archive", "true")
```

File: src/core/external.scala (hunk 6 above)
Comment (odisseus) [reply src/core/external.scala:75]: See #1116.

**Comment by propensive** [comment]
> Regarding the usage of IPFS gateways vs setting up a local node, I think the local node should be used as much as possible. This will avoid the strain on the gateways and make the user independent of them. There is even an [opinion](https://medium.com/pinata/the-ipfs-gateway-problem-64bbe7eb8170) that public gateways do a disservice to the IPFS community.

Yes, I would rather use the node if we can. But if it's a choice between downloading a 10K file over HTTP and a large download of IPFS, which might not work due to network restrictions, then I would rather download with HTTP.
