### PR TITLE
Fixed resolution of the local checkout directory for repositories.

### LINKED ISSUE #1462: Bloop configuration is broken for forks of local repositories
This is the reason why the repo-fork test fails.

**Before fork:**
```
"sources": [
    "/home/user/.cache/fury/sources/C25973C9AED0F365/src/core"
],
```

**After fork:**
```
"sources": [
    "/home/user/devel/fury/test/tmp/repo-fork/app/home/user/devel/fury/test/tmp/repo-fork/app/library-local/src/core"
],
```

This issue was caused by PR #1451.

### PR DESCRIPTION
**Pull request by odisseus**
Fixes #1462.

### CODE REVIEW

File: src/core/sourceRepo.scala [hunk 1]
```diff
@@ -63,7 +63,7 @@ case class Repo(id: RepoId, remote: Remote, branch: Branch, commit: Commit, loca
     Snapshot(id, remote, localDir(layout), commit, branch, List())
 
   def localDir(layout: Layout)(implicit log: Log): Option[GitDir] =
-    local.map { p => GitDir(p in layout.baseDir)(layout.env) }
```
Comment (propensive) [inline src/core/sourceRepo.scala:66]: I wonder if we should rewrite `in`. Is what it's currently doing ever useful?

**Review by propensive — APPROVED** [review]

File: src/core/sourceRepo.scala (hunk 1 above)
Comment (odisseus) [reply src/core/sourceRepo.scala:66]: I'm not sure. Currently, `a in b` is equivalent to `b / a.value`. However, the method `/` accepts strings which may contain something like `..` and don't even have to be valid paths.
