### PR TITLE
Include `module` in Target, and remove `kind`

### LINKED ISSUE #897: use `Try` for config file migrations
The OGDL `migrate` methods can throw exceptions, but should instead `flatMap` over `Try`s.

### LINKED ISSUE #1428: simplify `Target`s
They seem to copy too much information.

### PR DESCRIPTION
**Pull request by propensive**
Start of some cleanup to design of targets.

### CODE REVIEW

File: src/module/module.scala [hunk 1]
```diff
@@ -123,20 +127,19 @@ case class ModuleCli(cli: Cli)(implicit log: Log) {
...
     module      <- ~call(HiddenArg).toOption.map { h => module.copy(hidden = h) }.getOrElse(module)
     layer       <- ~Layer(_.projects(project.id).modules).modify(layer)(_ + module)
     layer       <- ~(Layer(_.projects(project.id).main)(layer) = Some(module.id))
 
-    layer       <- if(project.compiler.isEmpty && compilerRef != ModuleRef.JavaRef) {
+    layer       <- if(project.compiler.isEmpty && compilerRef.isDefined) {
                      ~Layer(_.projects(project.id).compiler).modify(layer) { v =>
-                       log.info(msg"Setting default compiler for project ${project.id} to ${compilerRef}")
-                       Some(compilerRef)
+                       log.info(msg"Setting default compiler for ${project.id} to ${module.compiler}")
```
Comment (odisseus) [inline src/module/module.scala:141]: This single line caused changes in 22 integration tests. Can it be extracted into a separate pull request?

Comment (propensive) [reply src/module/module.scala:141]: It was never significant enough to warrant a PR, and the `check` files will merge easily anyway.

**Comment by propensive** [comment]
I'm going to have to postpone the more recent changes I had planned for this PR, and merge this as-is. It doesn't change much (yet), but I'll open a new PR with further WIP changes.
